src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $release_date;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $length;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $trailer;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $synopsis;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $budget;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $box_office;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentary", mappedBy="fk_movie")
     */
    private $fk_commentary;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MovieWorker", mappedBy="fk_movie")
     */
    private $movieWorkers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $language;

    
      /****************************************/
     /* Manual Generated methods / variables */
    /****************************************/
    public function __toString()
    {
        return $this->title;
    }


      /**************************************/
     /*  AutoGenerated methods / variables */
    /**************************************/
    public function __construct()
    {
        $this->fk_commentary = new ArrayCollection();
        $this->movieWorkers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(?\DateTimeInterface $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getLength(): ?\DateTimeInterface
    {
        return $this->length;
    }

    public function setLength(?\DateTimeInterface $length): self
    {
        $this->length = $length;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(?string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getTrailer(): ?string
    {
        return $this->trailer;
    }

    public function setTrailer(?string $trailer): self
    {
        $this->trailer = $trailer;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getBudget(): ?int
    {
        return $this->budget;
    }

    public function setBudget(?int $budget): self
    {
        $this->budget = $budget;

        return $this;
    }

    public function getBoxOffice(): ?int
    {
        return $this->box_office;
    }

    public function setBoxOffice(?int $box_office): self
    {
        $this->box_office = $box_office;

        return $this;
    }

    /**
     * @return Collection|Commentary[]
     */
    public function getFkCommentary(): Collection
    {
        return $this->fk_commentary;
    }

    public function addFkCommentary(Commentary $fkCommentary): self
    {
        if (!$this->fk_commentary->contains($fkCommentary)) {
            $this->fk_commentary[] = $fkCommentary;
            $fkCommentary->setFkMovie($this);
        }

        return $this;
    }

    public function removeFkCommentary(Commentary $fkCommentary): self
    {
        if ($this->fk_commentary->contains($fkCommentary)) {
            $this->fk_commentary->removeElement($fkCommentary);
            // set the owning side to null (unless already changed)
            if ($fkCommentary->getFkMovie() === $this) {
                $fkCommentary->setFkMovie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|MovieWorker[]
     */
    public function getMovieWorkers(): Collection
    {
        return $this->movieWorkers;
    }

    public function addMovieWorker(MovieWorker $movieWorker): self
    {
        if (!$this->movieWorkers->contains($movieWorker)) {
            $this->movieWorkers[] = $movieWorker;
            $movieWorker->setFkMovie($this);
        }

        return $this;
    }

    public function removeMovieWorker(MovieWorker $movieWorker): self
    {
        if ($this->movieWorkers->contains($movieWorker)) {
            $this->movieWorkers->removeElement($movieWorker);
            // set the owning side to null (unless already changed)
            if ($movieWorker->getFkMovie() === $this) {
                $movieWorker->setFkMovie(null);
            }
        }

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): self
    {
        $this->language = $language;

        return $this;
    }
}

src/Form/MovieType.php
<?php

namespace App\Form;

use App\Entity\Movie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Intl\Intl;

class MovieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $languages = Intl::getLanguageBundle()->getLanguageNames();
        $builder
            ->add('title')
            ->add('release_date')
            ->add('language', ChoiceType::class, array(
                'placeholder' => '',
                'choices' => array_flip($languages),
                'label'=>'language'
            ))
            ->add('length')
            ->add('poster')
            ->add('trailer')
            ->add('synopsis')
            ->add('budget')
            ->add('box_office')
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Movie::class,
        ]);
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\Form\MovieType;
use App\Repository\MovieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\Commentary;
use App\Form\CommentaryType;
use App\Repository\CommentaryRepository;
use App\Controller\CommentaryController;

/**
 * @Route("/movie")
 */
class MovieController extends AbstractController
{
    /**
     * @Route("/", name="movie_index", methods={"GET"})
     */
    public function index(MovieRepository $movieRepository): Response
    {
        return $this->render('movie/index.html.twig', ['movies' => $movieRepository->findAll()]);
    }

    /**
     * @Route("/new", name="movie_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $movie = new Movie();
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($movie);
            $entityManager->flush();

            return $this->redirectToRoute('movie_index');
        }

        return $this->render('movie/new.html.twig', [
            'movie' => $movie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="movie_show", methods={"GET","POST"})
     */
    public function show(Movie $movie, CommentaryController $commentary, Request $request): Response
    {
        /* Copy of method new() from CommentaryController
        TODO: refactor this
        */
        $commentary = new Commentary();
        $commentary->setFkMovie($movie);
        $form = $this->createForm(CommentaryType::class, $commentary);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($commentary);
            $entityManager->flush();
        }
        

        return $this->render('movie/show.html.twig', ['movie' => $movie, 'form'=>$form->createView()]);
    }

    /**
     * @Route("/{id}/edit", name="movie_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Movie $movie): Response
    {
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('movie_index', ['id' => $movie->getId()]);
        }

        return $this->render('movie/edit.html.twig', [
            'movie' => $movie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="movie_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Movie $movie): Response
    {
        if ($this->isCsrfTokenValid('delete'.$movie->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($movie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('movie_index');
    }
}

templates/movie/_delete_form.html.twig
<form method="post" action="{{ path('movie_delete', {'id': movie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ movie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/movie/_form.html.twig
{{ form_start(form) }}

<div class="offset-0.5 col-7">
    {{ form_label(form.title, 'Titre') }}
    {{ form_widget(form.title, {'attr': {'class': 'title_field'}}) }}

    {{ form_label(form.language, 'Langue') }}
    {{ form_widget(form.language, {'attr': {'class': 'language_field'}}) }}

    {{ form_label(form.release_date, 'Date de sortie') }}
    {{ form_widget(form.release_date, {'attr': {'class': 'release_date_field'}}) }}

    {{ form_label(form.length, 'Durée') }}
    {{ form_widget(form.length, {'attr': {'class': 'length_field'}}) }}

    {{ form_label(form.poster, 'Affiche') }}
    {{ form_widget(form.poster, {'attr': {'class': 'poster_field'}}) }}

    {{ form_label(form.trailer, 'Bande Annonce') }}
    {{ form_widget(form.trailer, {'attr': {'class': 'trailer_field'}}) }}

    {{ form_label(form.synopsis, 'Synopsis') }}
    {{ form_widget(form.synopsis, {'attr': {'class': 'synopsis_field'}}) }}

    {{ form_label(form.budget, 'Budget') }}
    {{ form_widget(form.budget, {'attr': {'class': 'budget_field'}}) }}

    {{ form_label(form.box_office, 'Box Office') }}
    {{ form_widget(form.box_office, {'attr': {'class': 'box_office_field'}}) }}
</div>

    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/movie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Movie{% endblock %}

{% block body %}
    <h1>Edit Movie</h1>

    {{ include('movie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('movie_index') }}">back to list</a>

    {{ include('movie/_delete_form.html.twig') }}
{% endblock %}

templates/movie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movie index{% endblock %}

{% block body %}
    <h1>Movie index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Langue</th>
                <th>Date de sortie</th>
                <th>Durée</th>
                <th>Poster</th>
                <th>Trailer</th>
                <th>Synopsis</th>
                <th>Budget</th>
                <th>Box_office</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for movie in movies %}
            <tr>
                <td>{{ movie.title }}</td>
                <td>{{ movie.language }}</td>
                <td>{{ movie.releaseDate ? movie.releaseDate|date('Y-m-d') : '' }}</td>
                <td>{{ movie.length ? movie.length|date('H:i:s') : '' }}</td>
                <td>{{ movie.poster }}</td>
                <td>{{ movie.trailer }}</td>
                <td>{{ movie.synopsis }}</td>
                <td>{{ movie.budget }}</td>
                <td>{{ movie.boxOffice }}</td>
                <td>
                    <a href="{{ path('movie_show', {'id': movie.id}) }}">show</a>
                    <a href="{{ path('movie_edit', {'id': movie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('movie_new') }}">Create new</a>
{% endblock %}

templates/movie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Movie{% endblock %}

{% block body %}
    <h1 style="text-align:center">Ajouter un film</h1>

    {{ include('movie/_form.html.twig') }}

    <a class="btn" href="{{ path('movie_index') }}">Annuler</a>
    
{% endblock %}

templates/movie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movie{% endblock %}

{% block body %}
    <h1>Movie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Titre</th>
                <td>{{ movie.title }}</td>
            </tr>
            <tr>
                <th>Langue</th>
                <td>{{ movie.language }}</td>
            </tr>
            <tr>
                <th>Date de sortie</th>
                <td>{{ movie.releaseDate ? movie.releaseDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Durée</th>
                <td>{{ movie.length ? movie.length|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Affiche</th>
                <td>{{ movie.poster }}</td>
            </tr>
            <tr>
                <th>Bande Annonce</th>
                <td>{{ movie.trailer }}</td>
            </tr>
            <tr>
                <th>Synopsis</th>
                <td>{{ movie.synopsis }}</td>
            </tr>
            <tr>
                <th>Budget</th>
                <td>{{ movie.budget }}</td>
            </tr>
            <tr>
                <th>Box_office</th>
                <td>{{ movie.boxOffice }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('movie_index') }}">back to list</a>

    <a href="{{ path('movie_edit', {'id': movie.id}) }}">edit</a>

    {{ include('movie/_delete_form.html.twig') }}
    
    {{ render(controller(
        'App\\Controller\\CommentaryController::index',
        { 'id_movie': movie.id, }
    )) }}

    {% include "commentary/new.html.twig" %}

    

    {{ dump(movie) }}
{% endblock %}