src/Entity/Commentary.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentaryRepository")
 */
class Commentary
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_datetime;

    /**
     * @ORM\Column(type="smallint")
     */
    private $score;

    /**
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Movie", inversedBy="fk_commentary")
     */
    private $fk_movie;


      /****************************************/
     /* Manual Generated methods / variables */
    /****************************************/


    
      /**************************************/
     /*  AutoGenerated methods / variables */
    /**************************************/
    public function __construct()
    {
        $this->movie = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getCreatedDatetime(): ?\DateTimeImmutable
    {
        return $this->created_datetime;
    }

    public function setCreatedDatetime(\DateTimeImmutable $created_datetime): self
    {
        $this->created_datetime =  new \DateTimeImmutable("now");

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(int $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * @return Collection|Movie[]
     */
    public function getMovie(): Collection
    {
        return $this->movie;
    }

    public function addMovie(Movie $movie): self
    {
        if (!$this->movie->contains($movie)) {
            $this->movie[] = $movie;
            $movie->setFkCommentary($this);
        }

        return $this;
    }

    public function removeMovie(Movie $movie): self
    {
        if ($this->movie->contains($movie)) {
            $this->movie->removeElement($movie);
            // set the owning side to null (unless already changed)
            if ($movie->getFkCommentary() === $this) {
                $movie->setFkCommentary(null);
            }
        }

        return $this;
    }

    public function getFkMovie(): ?Movie
    {
        return $this->fk_movie;
    }

    public function setFkMovie(?Movie $fk_movie): self
    {
        $this->fk_movie = $fk_movie;

        return $this;
    }
}

src/Form/CommentaryType.php
<?php

namespace App\Form;

use App\Entity\Commentary;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class CommentaryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pseudo')
            ->add('created_datetime')
            ->add('score', ChoiceType::class, [
                'placeholder' => 'Votre note /5',
                'choices' => [
                    '0' => 0,
                    '1' => 1,
                    '2' => 2,
                    '3' => 3,
                    '4' => 4,
                    '5' => 5,
                ],
            ])
            ->add('comment')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commentary::class,
        ]);
    }
}

src/Controller/CommentaryController.php
<?php

namespace App\Controller;

use App\Entity\Commentary;
use App\Form\CommentaryType;
use App\Repository\CommentaryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


use App\Entity\Movie;
use App\Form\MovieType;
use App\Repository\MovieRepository;
use App\Controller\MovieController;

/**
 * @Route("/commentary")
 */
class CommentaryController extends AbstractController
{
    /**
     * @Route("/", name="commentary_index", methods={"GET"})
     */
    public function index(CommentaryRepository $commentaryRepository, $id_movie): Response
    {
        return $this->render(
            'commentary/index.html.twig',
            ['commentaries' => $commentaryRepository->findByMovie($id_movie)]
        );
    }

    /**
     * @Route("/new", name="commentary_new", methods={"GET","POST"})
     */
    public function new(Request $request, Movie $movie): Response
    {
        $commentary = new Commentary();
        $commentary->setFkMovie($movie);
        $form = $this->createForm(CommentaryType::class, $commentary);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($commentary);
            $entityManager->flush();

            //return $this->redirectToRoute('commentary_index');
        }

        return $this->render('commentary/new.html.twig', [
            'commentary' => $commentary,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commentary_show", methods={"GET"})
     */
    public function show(Commentary $commentary): Response
    {
        return $this->render('commentary/show.html.twig', ['commentary' => $commentary]);
    }

    /**
     * @Route("/{id}/edit", name="commentary_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Commentary $commentary): Response
    {
        $form = $this->createForm(CommentaryType::class, $commentary);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('commentary_index', ['id' => $commentary->getId()]);
        }

        return $this->render('commentary/edit.html.twig', [
            'commentary' => $commentary,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commentary_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Commentary $commentary): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentary->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($commentary);
            $entityManager->flush();
        }

        return $this->redirectToRoute('commentary_index');
    }
}

templates/commentary/_delete_form.html.twig
<form method="post" action="{{ path('commentary_delete', {'id': commentary.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentary.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commentary/_form.html.twig
{{ form_start(form) }}

<div class="row">
    <div class="col-3">
        {{ form_row(form.pseudo) }}
    </div>
    <div class="col-2">
        {{ form_label(form.score, 'Note') }}
        {{ form_widget(form.score) }}

    </div>
</div>

<div class="row">
    <div class="col-6">
        {{ form_label(form.comment, 'Commentaire') }}
        {{ form_widget(form.comment, { 'attr': {'style': 'height: 100px'}}) }}
    </div>
</div>

<!-- 'class: d-none' hide the field created_datetime which is automatically set to current time-->
{{ form_label(form.created_datetime, 'created_datetime',{'label_attr': {'class': 'd-none'}}) }}
{{ form_widget(form.created_datetime,{ 'attr': {'class': 'd-none'} }) }}

<button class="btn">{{ button_label|default('Poster') }}</button>

{{ form_end(form)}}

templates/commentary/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commentary{% endblock %}

{% block body %}
    <h1>Edit Commentary</h1>

    {{ include('commentary/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commentary_index') }}">back to list</a>

    {{ include('commentary/_delete_form.html.twig') }}
{% endblock %}

templates/commentary/index.html.twig
{% block title %}<h1>Commentaires</h1>{% endblock %}

{% block body %}

<div class="container">
    {% for commentary in commentaries %}
    <div class="row border rounded w-50 mb-3">
        <div class="col-3 text-center pt-1">
            <img class="rounded-circle" src="https://via.placeholder.com/80" alt="avatar">
        </div>

        <div class="col-9">
                {% for i in 1..5 %}
                    {% if i <= commentary.score %}
                    <span class="text-warning fa fa-star"></span>
                    {% else %}
                    <span class="fa fa-star"></span>
                    {% endif %}
                {% endfor %}            
                <p><b>{{ commentary.pseudo }}</b> - {{ commentary.createdDatetime|date('d M Y à H:i:s') }}</p>
                <p>{{ commentary.comment }}</p>
        </div>
    </div>
    {% else %}
    <tr>
        <td colspan="6">Aucun commentaire</td>
    </tr>
    {% endfor %}
</div>

{% endblock %}

templates/commentary/new.html.twig
{% block body %}
<div class="container">
    <h2>Ajouter un commentaire</h2>

    {{ include('commentary/_form.html.twig') }}
</div>
{% endblock %}

templates/commentary/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentary{% endblock %}

{% block body %}
    <h1>Commentary</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commentary.id }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ commentary.pseudo }}</td>
            </tr>
            <tr>
                <th>Created_datetime</th>
                <td>{{ commentary.createdDatetime ? commentary.createdDatetime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Score</th>
                <td>{{ commentary.score }}</td>
            </tr>
            <tr>
                <th>Comment</th>
                <td>{{ commentary.comment }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('commentary_index') }}">back to list</a>

    <a href="{{ path('commentary_edit', {'id': commentary.id}) }}">edit</a>

    {{ include('commentary/_delete_form.html.twig') }}
{% endblock %}